//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
namespace AnetMerchantBoarding.ANetAPI
{
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("ErrorResponse", Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public partial class ANetApiResponse
    {

        /// <remarks/>
        public string refId;

        /// <remarks/>
        public messagesType messages;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public partial class messagesType
    {

        /// <remarks/>
        public messageTypeEnum resultCode;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("message")]
        public messagesTypeMessage[] message;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public enum messageTypeEnum
    {

        /// <remarks/>
        Ok,

        /// <remarks/>
        Error,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public partial class messagesTypeMessage
    {

        /// <remarks/>
        public string code;

        /// <remarks/>
        public string text;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public partial class deviceInfoType
    {

        /// <remarks/>
        public deviceTypeEnum deviceType;

        /// <remarks/>
        public string state;

        /// <remarks/>
        public string zip;

        /// <remarks/>
        public string country;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public enum deviceTypeEnum
    {

        /// <remarks/>
        Unconfigured,

        /// <remarks/>
        UnattendedTerminal,

        /// <remarks/>
        SelfServiceTerminal,

        /// <remarks/>
        ElectronicCashRegister,

        /// <remarks/>
        PCBasedTerminal,

        /// <remarks/>
        Airpay,

        /// <remarks/>
        WirelessPOS,

        /// <remarks/>
        WebSite,

        /// <remarks/>
        DialTerminal,

        /// <remarks/>
        VirtualTerminal,

        /// <remarks/>
        StoreController,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public partial class serviceBuyRateProgramsType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("serviceBuyRateProgram", IsNullable = true)]
        public serviceBuyRateProgramType[] serviceBuyRateProgram;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public partial class serviceBuyRateProgramType
    {

        /// <remarks/>
        public int id;

        /// <remarks/>
        public bool isDefault;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isDefaultSpecified;

        /// <remarks/>
        public bool isSelfProvisioning;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isSelfProvisioningSpecified;

        /// <remarks/>
        public string description;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("fee")]
        public feeType[] fees;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public partial class feeType
    {

        /// <remarks/>
        public int id;

        /// <remarks/>
        public bool singleTiered;

        /// <remarks/>
        public feeRateTypeType rateType;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("feeTier")]
        public feeTierType[] tiers;

        /// <remarks/>
        public string description;

        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool settable;

        public feeType()
        {
            this.settable = false;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public partial class feeRateTypeType
    {

        /// <remarks/>
        public int id;

        /// <remarks/>
        public string description;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public partial class feeTierType
    {

        /// <remarks/>
        public int id;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified;

        /// <remarks/>
        public int lowerThreshold;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lowerThresholdSpecified;

        /// <remarks/>
        public decimal sellRate;

        /// <remarks/>
        public decimal buyRate;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool buyRateSpecified;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public partial class serviceType
    {

        /// <remarks/>
        public int id;

        /// <remarks/>
        public string description;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("optOut", typeof(bool))]
        [System.Xml.Serialization.XmlElementAttribute("serviceBuyRatePrograms", typeof(serviceBuyRateProgramsType))]
        public object Item;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public partial class salesRepType
    {

        /// <remarks/>
        public string salesRepName;

        /// <remarks/>
        public string salesRepId;

        /// <remarks/>
        public decimal salesRepCommission;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public partial class fieldConfigType
    {

        /// <remarks/>
        public string fieldName;

        /// <remarks/>
        public int minLength;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool minLengthSpecified;

        /// <remarks/>
        public int maxLength;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxLengthSpecified;

        /// <remarks/>
        public string description;

        /// <remarks/>
        public string displayLabel;

        /// <remarks/>
        public string fieldValue;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public partial class processorType
    {

        /// <remarks/>
        public int id;

        /// <remarks/>
        public string displayName;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("processorFieldConfig")]
        public fieldConfigType[] procConfig;

        /// <remarks/>
        public int acquirerId;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool acquirerIdSpecified;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public partial class paymentGroupingType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("paymentType", IsNullable = false)]
        public string[] paymentTypes;

        /// <remarks/>
        public processorType processor;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public partial class billingInfoType
    {

        /// <remarks/>
        public string nameOnBankAccount;

        /// <remarks/>
        public resellerBankAccountTypeEnum bankAccountType;

        /// <remarks/>
        public bankAccountOwnerTypeEnum bankAccountOwnerType;

        /// <remarks/>
        public string bankABACode;

        /// <remarks/>
        public string bankAccountNumber;

        /// <remarks/>
        public string bankName;

        /// <remarks/>
        public string bankCity;

        /// <remarks/>
        public string bankState;

        /// <remarks/>
        public string bankZip;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public enum resellerBankAccountTypeEnum
    {

        /// <remarks/>
        Checking,

        /// <remarks/>
        Savings,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public enum bankAccountOwnerTypeEnum
    {

        /// <remarks/>
        Personal,

        /// <remarks/>
        Business,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public partial class ownerInfoType
    {

        /// <remarks/>
        public string name;

        /// <remarks/>
        public string title;

        /// <remarks/>
        public addressType address;

        /// <remarks/>
        public string phone;

        /// <remarks/>
        public string ssn;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public partial class addressType
    {

        /// <remarks/>
        public string streetAddress;

        /// <remarks/>
        public string city;

        /// <remarks/>
        public string state;

        /// <remarks/>
        public string zip;

        /// <remarks/>
        public string country;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public partial class businessInfoType
    {

        /// <remarks/>
        public businessTypeEnum businessType;

        /// <remarks/>
        public string taxId;

        /// <remarks/>
        public int ageOfBusiness;

        /// <remarks/>
        public string productsSold;

        /// <remarks/>
        public string sicCode;

        /// <remarks/>
        public int marketTypeId;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public enum businessTypeEnum
    {

        /// <remarks/>
        SoleProprietorShip,

        /// <remarks/>
        PartnerShip,

        /// <remarks/>
        Corporation,

        /// <remarks/>
        NonProfit,

        /// <remarks/>
        Trust,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public partial class merchantType
    {

        /// <remarks/>
        public string name;

        /// <remarks/>
        public string referenceId;

        /// <remarks/>
        public addressType businessAddress;

        /// <remarks/>
        public string phone;

        /// <remarks/>
        public string fax;

        /// <remarks/>
        public string email;

        /// <remarks/>
        public businessInfoType businessInfo;

        /// <remarks/>
        public ownerInfoType ownerInfo;

        /// <remarks/>
        public billingInfoType billingInfo;

        /// <remarks/>
        public paymentGroupingType paymentGrouping;

        /// <remarks/>
        public salesRepType salesRep;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("merchantService")]
        public serviceType[] services;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("DeviceInfo")]
        public deviceInfoType[] deviceList;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public partial class resellerAuthenticationType
    {

        /// <remarks/>
        public string name;

        /// <remarks/>
        public string apiKey;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    public partial class ANetApiRequest
    {

        /// <remarks/>
        public resellerAuthenticationType resellerAuthentication;

        /// <remarks/>
        public string refId;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public partial class isAliveRequest
    {

        /// <remarks/>
        public string refId;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public partial class isAliveResponse : ANetApiResponse
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public partial class resellerCreateMerchantRequest : ANetApiRequest
    {

        /// <remarks/>
        public merchantType merchant;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public partial class resellerCreateMerchantResponse : ANetApiResponse
    {

        /// <remarks/>
        public int merchantId;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public partial class getServiceBuyRateProgramsRequest : ANetApiRequest
    {

        /// <remarks/>
        public int serviceTypeId;

        /// <remarks/>
        public int marketTypeId;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool marketTypeIdSpecified;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public partial class getServiceBuyRateProgramsResponse : ANetApiResponse
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("serviceBuyRateProgram")]
        public serviceBuyRateProgramType[] serviceBuyRatePrograms;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public partial class getResellerProcessorsRequest : ANetApiRequest
    {

        /// <remarks/>
        public int marketTypeId;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public partial class getResellerProcessorsResponse : ANetApiResponse
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("processor")]
        public processorType[] processors;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public partial class getResellerServicesRequest : ANetApiRequest
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", IsNullable = false)]
    public partial class getResellerServicesResponse : ANetApiResponse
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("merchantService")]
        public serviceType[] services;
    }
}
